### ISSUE TITLE
Feature Request: Search feature for invites

### ISSUE THREAD

**Issue by CSchoel** [LiScI-Lab/Guardian-of-Times#1]
Currently users can be added to a team by scrolling through a list of all users and clicking the relevant users.

This will not be feasible anymore when we have multiple large projects in GoT (think algorithms and data structures or large bridging courses).

:arrow_right: Users need to be able to filter the invite list by real name, username and e-mail (preferably from a single search field that searchs in all relevant attributes).

**Comment by njustus** [comment]
You're totally right.. Without a search field the member's list is pretty pointless..
I've added a search field ;)
